#!/usr/bin/env bash

set -e

mkdir -p /run/php
touch /var/log/xdebug.log
chown www-data:www-data /var/log/xdebug.log
chmod 666 /var/log/xdebug.log

exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
